import 'dotenv/config'
import bcrypt from 'bcryptjs'
import { pool, query } from './db.js'
import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { randomUUID } from 'node:crypto'
import { sha256 } from './lib/security.js'

const dir=path.dirname(fileURLToPath(import.meta.url))
await query(await readFile(path.join(dir,'../migrations/001_initial.sql'),'utf8'))
const email=process.env.SEED_ADMIN_EMAIL; const password=process.env.SEED_ADMIN_PASSWORD
if(!email||!password||password.length<16) throw new Error('Set SEED_ADMIN_EMAIL and a SEED_ADMIN_PASSWORD of at least 16 characters')
await query(`INSERT INTO admin_users(email,full_name,password_hash,role) VALUES($1,$2,$3,'SUPER_ADMIN') ON CONFLICT(email) DO NOTHING`,[email,'Ruthikisha Super Admin',await bcrypt.hash(password,12)])
const contentDefaults={'site.companyName':'Ruthikisha Travel','home.heroTitle':'YOUR JOURNEY STARTS HERE','home.heroSubtitle':'Comfortable journeys. Thoughtfully designed.','about.story':'We’re a Coimbatore-based travel team building a better way to explore South India. We bring trusted bus operators, comfortable journeys and thoughtful service together, so you can spend less time figuring it out and more time looking forward.','contact.phone':'+91 422 456 7890','contact.email':'hello@ruthikishatravel.in','contact.address':'Coimbatore, Tamil Nadu, India','contact.supportHours':'Our local support team is available every day, 8am–8pm.','policies.cancellation':'Contact Ruthikisha Travel support for cancellation options.','policies.terms':'Terms and conditions are being prepared by the operator.','policies.privacy':'Privacy information is being prepared by the operator.','booking.rules':'Please check passenger names, dates, and seat selections before payment.'}
for(const [key,value] of Object.entries(contentDefaults))await query('INSERT INTO website_settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO NOTHING',[key,JSON.stringify(value)])
if(process.env.SEED_DEMO_DATA!=='true'){
  console.log(`Seeded initial admin ${email} and website content. No sample operating data was created; add the real fleet and services in Admin.`)
  await pool.end()
}else{
const buses=[['Ruthikisha Horizon','RT-101','TN-38-AB-4101','AC Sleeper',36,'/images/WhatsApp%20Image%202026-09-29%20at%209.20.04%20AM.jpeg'],['Ruthikisha Vista','RT-102','TN-38-AB-4102','AC Seater',40,'/images/WhatsApp%20Image%202026-09-29%20at%209.20.05%20AM.jpeg'],['Ruthikisha Breeze','RT-103','TN-38-AB-4103','AC Seater',40,'/images/WhatsApp%20Image%202026-09-29%20at%209.20.04%20AM.jpeg'],['Ruthikisha Classic','RT-104','TN-38-AB-4104','Non-AC Seater',36,'/images/WhatsApp%20Image%202026-09-29%20at%209.20.05%20AM.jpeg'],['Ruthikisha Comfort','RT-105','TN-38-AB-4105','AC Sleeper',32,'/images/WhatsApp%20Image%202026-09-29%20at%209.20.04%20AM.jpeg']]
for(const [name,bus_number,registration_number,type,total_seats,photo_path] of buses){const b=await query('INSERT INTO buses(name,bus_number,registration_number,type,total_seats,photo_path,amenities) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(bus_number) DO UPDATE SET name=EXCLUDED.name RETURNING id',[name,bus_number,registration_number,type,total_seats,photo_path,JSON.stringify(['Air conditioning','USB charging','Reading lights'])]); for(let n=1;n<=total_seats;n++) await query('INSERT INTO bus_seats(bus_id,seat_number) VALUES($1,$2) ON CONFLICT DO NOTHING',[b.rows[0].id,String(n).padStart(2,'0')])}
const routes=[['Coimbatore','Chennai',510,540],['Coimbatore','Kochi',190,300],['Coimbatore','Bengaluru',360,420],['Chennai','Bengaluru',350,390],['Coimbatore','Madurai',215,240]]
for(const [from,to,distance,duration] of routes) await query('INSERT INTO routes(from_city,to_city,route_name,stops,distance_km,estimated_duration_minutes) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(from_city,to_city) DO NOTHING',[from,to,`${from} - ${to}`,JSON.stringify([from,to]),distance,duration])
const allRoutes=(await query('SELECT id,from_city,to_city,estimated_duration_minutes FROM routes')).rows; const allBuses=(await query('SELECT id FROM buses ORDER BY bus_number')).rows
for(let i=0;i<allRoutes.length;i++) for(let j=0;j<allBuses.length;j++){const route=allRoutes[i]; const bus=allBuses[j]; const price=500+i*120;const departureHour=6+i;const departure=`${String(departureHour).padStart(2,'0')}:30`;const arrivalMinutes=(departureHour*60+30+route.estimated_duration_minutes)%1440;const arrival=`${String(Math.floor(arrivalMinutes/60)).padStart(2,'0')}:${String(arrivalMinutes%60).padStart(2,'0')}`;const existing=await query('SELECT id FROM schedules WHERE bus_id=$1 AND route_id=$2 AND starts_on=CURRENT_DATE AND departure_time=$3::time',[bus.id,route.id,departure]);let scheduleId=existing.rows[0]?.id;if(!scheduleId){const s=await query(`INSERT INTO schedules(bus_id,route_id,starts_on,ends_on,days_of_week,departure_time,arrival_time,duration_minutes,base_price) VALUES($1,$2,CURRENT_DATE,CURRENT_DATE+90,ARRAY[0,1,2,3,4,5,6]::smallint[],$3::time,$4::time,$5,$6) RETURNING id`,[bus.id,route.id,departure,arrival,route.estimated_duration_minutes,price]);scheduleId=s.rows[0].id}await query('INSERT INTO schedule_seats(schedule_id,seat_number,seat_type) SELECT $1,seat_number,seat_type FROM bus_seats WHERE bus_id=$2 ON CONFLICT DO NOTHING',[scheduleId,bus.id])}
const demoSchedule=(await query('SELECT id,travel_date FROM (SELECT id,CURRENT_DATE+7 AS travel_date FROM schedules WHERE active ORDER BY departure_time LIMIT 1) selected')).rows[0]
if(demoSchedule){const demoCustomers=[['Travel Demo One','+910000000001','guest1@example.test'],['Travel Demo Two','+910000000002','guest2@example.test'],['Travel Demo Three','+910000000003','guest3@example.test']];for(let i=0;i<demoCustomers.length;i++){const [fullName,phone,emailAddress]=demoCustomers[i];const customer=await query('INSERT INTO customers(full_name,phone,email) VALUES($1,$2,$3) ON CONFLICT(phone) DO UPDATE SET full_name=EXCLUDED.full_name,email=EXCLUDED.email RETURNING id',[fullName,phone,emailAddress]);const booking=await query(`INSERT INTO bookings(reference,customer_id,schedule_id,travel_date,status,payment_status,subtotal,fee,tax,total,access_token_hash,cancellation_reason,cancelled_at) SELECT $1,$2,$3,$4,'CANCELLED','FAILED',s.base_price,0,0,s.base_price,$5,'Sample record only',now() FROM schedules s WHERE s.id=$3 ON CONFLICT(reference) DO NOTHING RETURNING id,total`,[`RT-DEMO-${String(i+1).padStart(3,'0')}`,customer.rows[0].id,demoSchedule.id,demoSchedule.travel_date,sha256(randomUUID())]);if(booking.rowCount){await query(`INSERT INTO booking_passengers(booking_id,full_name,age,gender,seat_number) VALUES($1,$2,$3,$4,'99')`,[booking.rows[0].id,fullName,24+i,'PREFER_NOT_TO_SAY']);await query("INSERT INTO payments(booking_id,amount,status,gateway_payload) VALUES($1,$2,'FAILED',$3)",[booking.rows[0].id,booking.rows[0].total,JSON.stringify({sample:true})])}}}
console.log(`Seeded sample buses, routes, schedules, cancelled demo bookings and initial admin ${email}.`); await pool.end()
}
