import { useMemo, useState } from 'react'
import { Link, NavLink, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { buses, cities, formatINR } from './data/buses'
import { addBookingToHistory, readBooking, readHistory, saveBooking } from './utils/booking'
import './App.css'

function App() {
  const navigate = useNavigate()
  const [booking, setBooking] = useState(() => readBooking())
  const [trip, setTrip] = useState({ from: 'Coimbatore', to: 'Chennai', date: new Date().toISOString().slice(0, 10), returnDate: '', passengers: 1 })
  const updateBooking = (next) => { setBooking(next); saveBooking(next) }
  const search = () => navigate(`/search?from=${encodeURIComponent(trip.from)}&to=${encodeURIComponent(trip.to)}&date=${trip.date}`)
  const chooseBus = (bus) => { const next = { ...booking, bus, trip }; updateBooking(next); navigate(`/bus/${bus.id}`) }
  const selectSeats = (seats) => { updateBooking({ ...booking, seats }); navigate('/booking') }
  const finishPassengers = (passenger) => { const next = { ...booking, passenger, id: `RT${Date.now().toString().slice(-8)}`, total: booking.bus.price * booking.seats.length + 25 }; updateBooking(next); navigate('/payment') }
  const pay = () => { const next = { ...booking, status: 'Confirmed' }; updateBooking(next); addBookingToHistory(next); navigate('/booking-confirmation') }
  return <><Header /><Routes>
    <Route path="/" element={<Home trip={trip} setTrip={setTrip} search={search} />} />
    <Route path="/search" element={<SearchResults trip={trip} chooseBus={chooseBus} />} />
    <Route path="/bus/:id" element={<BusDetails chooseBus={chooseBus} />} />
    <Route path="/bus/:id/seats" element={<SeatSelection booking={booking} selectSeats={selectSeats} />} />
    <Route path="/booking" element={<PassengerBooking booking={booking} submit={finishPassengers} />} />
    <Route path="/payment" element={<Payment booking={booking} pay={pay} />} />
    <Route path="/booking-confirmation" element={<Confirmation booking={booking} />} />
    <Route path="/my-bookings" element={<MyBookings />} />
    <Route path="/about" element={<About />} />
    <Route path="/contact" element={<Contact />} />
    <Route path="*" element={<NotFound />} />
  </Routes><Footer /></>
}

function Header() {
  const [open, setOpen] = useState(false)
  return <header className="site-header"><div className="nav wrap"><Link className="brand" to="/" aria-label="Ruthikisha Travel home"><span className="brand-symbol">r.</span><span className="brand-name">ruthikisha<small>TRAVEL, THOUGHTFULLY</small></span></Link><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(!open)}>?</button><nav className={open ? 'nav-links open' : 'nav-links'}><NavLink to="/" onClick={() => setOpen(false)}>Home</NavLink><a href="/#routes" onClick={() => setOpen(false)}>Destinations</a><NavLink to="/about" onClick={() => setOpen(false)}>Our story</NavLink><NavLink to="/contact" onClick={() => setOpen(false)}>Contact</NavLink><NavLink to="/my-bookings" onClick={() => setOpen(false)}>My bookings</NavLink><Link className="button button-small" to="/#search" onClick={() => setOpen(false)}>Book a journey <span>?</span></Link></nav></div></header>
}
function SearchForm({ trip, setTrip, search }) {
  const set = (key, value) => setTrip({ ...trip, [key]: value })
  return <form className="search-form" onSubmit={(e) => { e.preventDefault(); search() }}>
    <label>FROM<select value={trip.from} onChange={(e) => set('from', e.target.value)}>{cities.map((city) => <option key={city}>{city}</option>)}</select></label>
    <button className="swap-button" type="button" title="Swap locations" onClick={() => setTrip({ ...trip, from: trip.to, to: trip.from })}>?</button>
    <label>TO<select value={trip.to} onChange={(e) => set('to', e.target.value)}>{cities.map((city) => <option key={city}>{city}</option>)}</select></label>
    <label>DEPARTURE<input required type="date" value={trip.date} onChange={(e) => set('date', e.target.value)} /></label>
    <label>RETURN <span className="optional">OPTIONAL</span><input type="date" min={trip.date} value={trip.returnDate} onChange={(e) => set('returnDate', e.target.value)} /></label>
    <label>TRAVELLERS<select value={trip.passengers} onChange={(e) => set('passengers', Number(e.target.value))}>{[1, 2, 3, 4, 5, 6].map((n) => <option key={n} value={n}>{n} {n === 1 ? 'passenger' : 'passengers'}</option>)}</select></label>
    <button className="button search-button">Find buses <span>?</span></button>
  </form>
}
function Home({ trip, setTrip, search }) {
  const popular = [['Coimbatore', 'Chennai', '8h 45m', 'From ?899', '01'], ['Coimbatore', 'Bangalore', '7h 30m', 'From ?749', '02'], ['Coimbatore', 'Kochi', '5h 45m', 'From ?599', '03'], ['Coimbatore', 'Madurai', '3h 45m', 'From ?399', '04']]
  return <><main>
    <section className="hero"><div className="hero-inner wrap"><div className="hero-copy"><div className="eyebrow"><span>?</span> A MORE THOUGHTFUL WAY TO TRAVEL</div><h1>Good journeys.<br /><em>Great beginnings.</em></h1><p>South India is closer than you think. Find a seat, settle in, and let the good miles roll.</p><a className="text-link light-link" href="#search">Find your next journey <span>?</span></a></div><div className="hero-visual"><div className="sun-disc"/><div className="hill hill-back"/><div className="hill hill-front"/><div className="road-line"/><div className="hero-stamp"><span>GO AT<br />YOUR OWN<br />PACE</span><b>?</b></div><div className="hero-caption">WESTERN GHATS � TAMIL NADU</div></div></div><div className="search-shell wrap" id="search"><div className="search-heading"><span>YOUR NEXT CHAPTER</span><strong>Where are we taking you?</strong></div><SearchForm trip={trip} setTrip={setTrip} search={search} /></div></section>
    <div className="trust-strip"><div className="wrap trust-inner"><span><b>?</b> 4.8 / 5 traveller rating</span><span><b>?</b> Punctuality you can count on</span><span><b>?</b> Comfort in every detail</span><span><b>?</b> Simple, secure booking</span></div></div>
    <section className="section wrap" id="routes"><div className="section-heading"><div><div className="eyebrow">ROUTES WE LOVE</div><h2>A good place to start.</h2><p>Familiar favourites and a few new ways to get there.</p></div><Link className="text-link" to="/search">See all routes <span>?</span></Link></div><div className="route-grid">{popular.map(([from, to, duration, fare, no]) => <button className="route-card" key={to} onClick={() => { setTrip({ ...trip, from, to }); document.querySelector('#search')?.scrollIntoView({ behavior: 'smooth' }) }}><div className="route-card-top"><span>JOURNEY {no}</span><span className="route-icon">?</span></div><h3>{from}<span> ? </span>{to}</h3><div className="route-meta"><span>{duration} journey</span><b>{fare}</b></div></button>)}</div></section>
    <section className="difference"><div className="wrap"><div className="eyebrow">THE RUTHIKISHA DIFFERENCE</div><h2>It�s the little things<br />that make the miles.</h2><div className="feature-grid">{[['01', 'A softer landing', 'Thoughtful comfort, generous legroom, and a little room to breathe.'], ['02', 'People who care', 'Local support that�s here to help, before and after you board.'], ['03', 'Good journeys, honestly priced', 'Clear fares, trusted operators, and no last-minute surprises.']].map(([number, title, text]) => <article className="feature" key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="offer-section wrap"><div className="offer-card"><div className="offer-art"><div className="offer-sun"/><div className="offer-moon">15<span>%</span></div><div className="offer-mountains"/></div><div className="offer-copy"><div className="eyebrow">A LITTLE SOMETHING FOR THE ROAD</div><h2>First journey?<br /><em>It�s on us.</em></h2><p>Take 15% off your first ride with code <b>RUTHI15</b>. A lovely reason to go.</p><Link className="button" to="/search">Find a bus <span>?</span></Link></div></div></section>
    <section className="section wrap"><div className="section-heading"><div><div className="eyebrow">KIND WORDS FROM THE ROAD</div><h2>We�ll let them tell you.</h2></div></div><div className="review-grid">{[['�Booking was a breeze, the bus was lovely, and we arrived right on time. That�s how travel should feel.�', 'Ananya R.', 'Coimbatore ? Chennai'], ['�The whole experience felt personal. Clean bus, kind crew, no surprises. I�ll definitely book again.�', 'Vikram S.', 'Bangalore ? Coimbatore'], ['�Comfortable seats and a beautiful route. Ruthikisha has made my weekend trips so much easier.�', 'Meera K.', 'Coimbatore ? Kochi']].map(([quote, name, route]) => <article className="review-card" key={name}><div className="stars">????? <small>5.0</small></div><p>{quote}</p><div className="review-person"><span className="avatar">{name[0]}</span><span><b>{name}</b><small>{route}</small></span></div></article>)}</div></section>
    <section className="faq-section wrap"><div><div className="eyebrow">GOOD TO KNOW</div><h2>A few things<br />you might be wondering.</h2><p>Still have a question? Our Coimbatore team is just a message away.</p><Link className="text-link" to="/contact">Talk to us <span>?</span></Link></div><div className="faq-list">{[['Can I cancel or change my booking?', 'You can contact our support team to understand the cancellation options available for your operator and ticket.'], ['When will I receive my ticket?', 'Your booking confirmation and ticket details are available as soon as checkout is complete.'], ['How do I choose my seat?', 'After picking a bus, choose from the available seats on the interactive seat map.']].map(([q, a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  </main></>
}
function SearchResults({ trip, chooseBus }) {
  const [params] = useSearchParams()
  const from = params.get('from') || trip.from, to = params.get('to') || trip.to
  const [sort, setSort] = useState('Recommended'), [acOnly, setAcOnly] = useState(false), [maxPrice, setMaxPrice] = useState(2000)
  const results = useMemo(() => { let list = buses.filter((bus) => bus.from === from && bus.to === to); if (acOnly) list = list.filter((bus) => /AC|Volvo/i.test(bus.type)); list = list.filter((bus) => bus.price <= maxPrice); if (sort === 'Lowest price') list.sort((a, b) => a.price - b.price); if (sort === 'Top rated') list.sort((a, b) => b.rating - a.rating); return list }, [from, to, acOnly, maxPrice, sort])
  return <main className="page wrap"><div className="eyebrow">A ROAD WELL CHOSEN</div><h1 className="page-title">{from} <em>?</em> {to}</h1><p className="page-subtitle">{results.length} buses for {params.get('date') || trip.date} � Pick the ride that feels right.</p><div className="results-layout"><aside className="filter-panel"><h3>Make it your kind of ride</h3><label className="check-label"><input type="checkbox" checked={acOnly} onChange={(e) => setAcOnly(e.target.checked)} /> Air conditioned</label><label className="filter-caption" htmlFor="price">MAX FARE <b>{formatINR(maxPrice)}</b></label><input id="price" type="range" min="400" max="2000" step="100" value={maxPrice} onChange={(e) => setMaxPrice(Number(e.target.value))} /><div className="filter-caption">AMENITIES</div><p>? Charging available</p><p>? Onboard support</p><div className="filter-caption">DEPARTURE</div><p>Evening � Night</p></aside><div className="bus-list"><div className="sort-bar"><span>{results.length} thoughtful {results.length === 1 ? 'option' : 'options'}</span><label>Sort by <select value={sort} onChange={(e) => setSort(e.target.value)}><option>Recommended</option><option>Lowest price</option><option>Top rated</option></select></label></div>{results.length ? results.map((bus) => <BusCard key={bus.id} bus={bus} chooseBus={chooseBus} />) : <div className="empty-state panel"><h2>No buses on this route just yet.</h2><p>Try Coimbatore to Chennai, Bangalore, Kochi or Madurai.</p><Link className="button" to="/">Change your search</Link></div>}</div></div></main>
}
function BusCard({ bus, chooseBus }) { return <article className="bus-card"><div className="bus-card-main"><div className="operator"><span className="operator-mark">{bus.operator[0]}</span><span><b>{bus.operator}</b><small>{bus.type}</small></span></div><div className="bus-times"><div><b>{bus.depart}</b><small>{bus.from}</small></div><span className="duration">{bus.duration}<i/></span><div><b>{bus.arrive}</b><small>{bus.to}</small></div></div><div className="bus-price"><span>From</span><b>{formatINR(bus.price)}</b><small>? {bus.rating} � {bus.seats} seats left</small></div></div><div className="bus-card-bottom"><span>{bus.amenities.join(' � ')}</span><button className="button button-small" onClick={() => chooseBus(bus)}>View bus <span>?</span></button></div></article> }
function BusDetails({ chooseBus }) { const { id } = useParams(); const bus = buses.find((item) => item.id === id); if (!bus) return <NotFound />; return <main className="page wrap"><div className="eyebrow">A CLOSER LOOK</div><h1 className="page-title">The {bus.operator} <em>experience.</em></h1><p className="page-subtitle">{bus.type} � ? {bus.rating} traveller rating � {bus.seats} seats available</p><div className="detail-columns"><section className="panel detail-panel"><h2>{bus.from} <em>?</em> {bus.to}</h2><div className="timeline"><div><b>{bus.depart}</b><span><strong>{bus.from}</strong><small>{bus.board[0]}</small></span></div><div><b>{bus.arrive}</b><span><strong>{bus.to}</strong><small>{bus.drop[0]}</small></span></div></div><h3>Comforts on board</h3><div className="amenity-list">{bus.amenities.map((a) => <span key={a}>? {a}</span>)}</div><h3>Boarding points</h3>{bus.board.map((point, index) => <p className="point-row" key={point}><b>{index ? '09:30 PM' : '09:00 PM'}</b> {point}</p>)}<h3>Dropping points</h3>{bus.drop.map((point, index) => <p className="point-row" key={point}><b>{index ? '06:45 AM' : '06:15 AM'}</b> {point}</p>)}<h3>Traveller notes</h3><p>�Clean, comfortable and right on time.� � recent Ruthikisha travellers</p></section><aside className="panel ride-summary"><div className="eyebrow">YOUR RIDE</div><h2>{bus.operator}</h2><p>{bus.type}</p><hr /><p>{bus.from} to {bus.to}</p><p>{bus.depart} � {bus.duration} � {bus.arrive}</p><h3>{formatINR(bus.price)} <small>/ seat</small></h3><button className="button full-button" onClick={() => chooseBus(bus)}>Select seats <span>?</span></button><small>Secure your favourite spot in just a moment.</small></aside></div></main> }
function SeatSelection({ booking, selectSeats }) { const { id } = useParams(); const bus = buses.find((item) => item.id === id) || booking?.bus; const [selected, setSelected] = useState(booking?.seats || []); if (!bus) return <NavigateHome />; const occupied = [3, 6, 11, 15, 18, 24]; const toggle = (number) => { if (occupied.includes(number)) return; setSelected((current) => current.includes(number) ? current.filter((seat) => seat !== number) : current.length < (booking?.trip?.passengers || 1) ? [...current, number] : current) }; return <main className="page wrap"><div className="eyebrow">MAKE IT YOURS</div><h1 className="page-title">Pick your <em>place.</em></h1><p className="page-subtitle">{bus.from} ? {bus.to} � {bus.operator} � Choose up to {booking?.trip?.passengers || 1} seat(s)</p><div className="seat-layout"><section className="panel seat-panel"><div className="driver">FRONT OF BUS <span>?</span></div><div className="seat-grid">{Array.from({ length: 24 }, (_, i) => i + 1).map((n) => <button key={n} type="button" aria-label={`Seat ${n}${occupied.includes(n) ? ', occupied' : selected.includes(n) ? ', selected' : ', available'}`} aria-pressed={selected.includes(n)} disabled={occupied.includes(n)} className={`seat ${occupied.includes(n) ? 'occupied' : ''} ${selected.includes(n) ? 'selected' : ''}`} onClick={() => toggle(n)}>{String(n).padStart(2, '0')}</button>)}</div><div className="seat-legend"><span><i/> Available</span><span><i className="selected-key"/> Selected</span><span><i className="occupied-key"/> Occupied</span></div></section><aside className="panel seat-summary"><div className="eyebrow">BOOKING SUMMARY</div><h2>{selected.length ? `${selected.length} seat${selected.length > 1 ? 's' : ''} selected` : 'Your seat, your choice.'}</h2>{selected.map((n) => <p key={n}>Seat {String(n).padStart(2, '0')} <b>{formatINR(bus.price)}</b></p>)}<hr /><p>Seat fare <b>{formatINR(bus.price * selected.length)}</b></p><button className="button full-button" disabled={!selected.length} onClick={() => selectSeats(selected)}>Continue <span>?</span></button><small>Passenger count is set in your search.</small></aside></div></main> }
function NavigateHome() { return <main className="page wrap"><h1 className="page-title">Choose your ride first.</h1><Link className="button" to="/search">Find a bus</Link></main> }
function PassengerBooking({ booking, submit }) { const [form, setForm] = useState({ name: '', email: '', phone: '' }); if (!booking?.bus || !booking?.seats?.length) return <NavigateHome />; const bus = booking.bus; const fare = bus.price * booking.seats.length; return <main className="page wrap"><div className="eyebrow">ALMOST THERE</div><h1 className="page-title">The details, then <em>off you go.</em></h1><div className="detail-columns"><form className="panel form-panel" onSubmit={(e) => { e.preventDefault(); submit(form) }}><h2>Passenger details</h2><p className="muted">Tell us who�s travelling. We�ll send the ticket to your inbox.</p><label>FULL NAME<input required autoComplete="name" placeholder="Name as on your ID" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>EMAIL ADDRESS<input required type="email" autoComplete="email" placeholder="you@example.com" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>PHONE NUMBER<input required type="tel" autoComplete="tel" minLength="10" placeholder="10 digit phone number" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><button className="button">Continue to payment <span>?</span></button></form><aside className="panel ride-summary"><div className="eyebrow">JOURNEY SUMMARY</div><h2>{bus.from} <em>?</em> {bus.to}</h2><p>{bus.operator} � {bus.type}</p><p>{booking.trip?.date} � {bus.depart} � {bus.arrive}</p><p>Seats {booking.seats.map((n) => String(n).padStart(2, '0')).join(', ')}</p><hr /><p>Seat fare <b>{formatINR(fare)}</b></p><p>Convenience fee <b>?25</b></p><h3>Total <b>{formatINR(fare + 25)}</b></h3></aside></div></main> }
function Payment({ booking, pay }) { const [method, setMethod] = useState('UPI'); const [value, setValue] = useState(''); if (!booking?.bus) return <NavigateHome />; return <main className="page wrap payment-page"><div className="eyebrow">A SECURE LITTLE CHECKOUT</div><h1 className="page-title">Make it <em>official.</em></h1><section className="panel form-panel"><h2>How would you like to pay?</h2><div className="payment-methods" role="group" aria-label="Payment method">{['UPI', 'Card', 'Net banking'].map((item) => <button key={item} type="button" className={method === item ? 'method-active' : ''} onClick={() => { setMethod(item); setValue('') }}>{item}</button>)}</div><label>{method === 'UPI' ? 'UPI ID' : method === 'Card' ? 'CARD NUMBER' : 'BANK NAME'}<input value={value} onChange={(e) => setValue(e.target.value)} placeholder={method === 'UPI' ? 'name@bank' : method === 'Card' ? '0000 0000 0000 0000' : 'Select your bank'} /></label>{method === 'Card' && <label>EXPIRY<input placeholder="MM / YY" /></label>}{method === 'Net banking' && <select aria-label="Select bank"><option>Choose your bank</option><option>State Bank of India</option><option>HDFC Bank</option><option>ICICI Bank</option><option>Axis Bank</option></select>}<button className="button" onClick={pay}>Pay {formatINR(booking.total)} <span>?</span></button><small className="payment-note">Demo checkout only � no real payment will be processed.</small></section></main> }
function Confirmation({ booking }) { if (!booking?.bus) return <NavigateHome />; return <main className="page wrap confirmation"><div className="success-mark">?</div><div className="eyebrow">YOU�RE ALL SET</div><h1 className="page-title">Your journey is <em>booked.</em></h1><p className="page-subtitle">A lovely trip is just around the corner.</p><section className="panel ticket"><div className="ticket-top"><span>BOOKING REFERENCE</span><b>{booking.id}</b></div><h2>{booking.bus.from} <em>?</em> {booking.bus.to}</h2><p>{booking.bus.operator} � {booking.trip?.date} � {booking.bus.depart}</p><hr /><div className="ticket-details"><span>Passenger<b>{booking.passenger?.name}</b></span><span>Seats<b>{booking.seats.map((n) => String(n).padStart(2, '0')).join(', ')}</b></span><span>Total paid<b>{formatINR(booking.total)}</b></span></div></section><div className="confirmation-actions"><button className="button" onClick={() => window.print()}>Download ticket <span>?</span></button><Link className="button button-outline" to="/my-bookings">View my bookings</Link><Link className="text-link" to="/">Go home</Link></div></main> }
function MyBookings() { const history = readHistory(); return <main className="page wrap"><div className="eyebrow">YOUR TRIPS</div><h1 className="page-title">A little road <em>time.</em></h1><p className="page-subtitle">Your Ruthikisha journeys, all in one place.</p>{history.length ? <div className="history-list">{history.map((item) => <article className="panel history-card" key={item.id}><div><span className="eyebrow">{item.id} � {item.trip?.date}</span><h2>{item.bus?.from} <em>?</em> {item.bus?.to}</h2><p>{item.bus?.operator} � Seats {item.seats?.join(', ')}</p></div><div className="history-end"><b>{formatINR(item.total)}</b><span className="status">{item.status || 'Confirmed'}</span></div></article>)}</div> : <section className="panel empty-state"><h2>Your next journey is waiting.</h2><p>When you book with us, your trips will show up right here.</p><Link className="button" to="/">Find your journey</Link></section>}</main> }
function About() { return <main className="page wrap"><div className="eyebrow">ROOTED IN COIMBATORE</div><h1 className="page-title">We believe the journey<br />should feel <em>like part of it.</em></h1><div className="about-layout"><section className="about-story"><p className="lead">Ruthikisha Travel began with a simple thought: getting there could feel a little more human.</p><p>We�re a Coimbatore-based travel team building a better way to explore South India. We bring trusted bus operators, comfortable journeys and thoughtful service together, so you can spend less time figuring it out and more time looking forward.</p><p>Whether it�s a weekend visit, a long-awaited reunion or a new city on your map, we�re happy to be part of the way.</p><Link className="button" to="/search">Find your next journey <span>?</span></Link></section><aside className="about-note"><span>11�00' N<br />76�57' E</span><b>Made with care<br />in Coimbatore.</b><i>?</i></aside></div></main> }
function Contact() { const [sent, setSent] = useState(false); return <main className="page wrap"><div className="eyebrow">A REAL PERSON IS RIGHT HERE</div><h1 className="page-title">Let�s have a <em>conversation.</em></h1><p className="page-subtitle">Questions, ideas, or just want to say hello? We�d love to hear from you.</p><div className="detail-columns contact-layout"><section className="panel contact-info"><h2>Come say hello.</h2><p><span>?</span> Coimbatore, Tamil Nadu, India</p><p><span>?</span> +91 422 456 7890</p><p><span>?</span> hello@ruthikishatravel.in</p><h3>Here when you need us</h3><p>Our local support team is available every day, 8am�8pm.</p><div className="eyebrow">QUICK QUESTIONS</div>{[['When will my ticket arrive?', 'Your confirmation is ready right after checkout.'], ['Can I change my trip?', 'Contact our team and we�ll guide you through your operator�s options.']].map(([q, a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section><form className="panel form-panel" onSubmit={(e) => { e.preventDefault(); setSent(true) }}><h2>Send us a note</h2>{sent ? <p className="success-message">Thanks for reaching out. Our Coimbatore team will be in touch soon.</p> : <><label>YOUR NAME<input required placeholder="Your name" /></label><label>EMAIL ADDRESS<input required type="email" placeholder="you@example.com" /></label><label>WHAT�S ON YOUR MIND?<textarea required rows="5" placeholder="Write us a note�" /></label><button className="button">Send your note <span>?</span></button></>}</form></div></main> }
function NotFound() { return <main className="page wrap not-found"><div className="eyebrow">WE TOOK A WRONG TURN</div><h1 className="page-title">This road ends <em>here.</em></h1><p className="page-subtitle">Let�s get you back to somewhere lovely.</p><Link className="button" to="/">Back to home <span>?</span></Link></main> }
function Footer() { return <footer className="site-footer"><div className="wrap footer-main"><div className="footer-brand"><Link className="brand brand-light" to="/"><span className="brand-symbol">r.</span><span className="brand-name">ruthikisha<small>TRAVEL, THOUGHTFULLY</small></span></Link><p>Good journeys begin here.<br />Coimbatore, Tamil Nadu, India.</p></div><div><span className="footer-label">EXPLORE</span><Link to="/search">Find a bus</Link><Link to="/about">Our story</Link><Link to="/contact">Get in touch</Link></div><div><span className="footer-label">YOUR TRAVEL</span><Link to="/my-bookings">My bookings</Link><Link to="/contact">Help & support</Link><a href="/#routes">Popular routes</a></div><div className="footer-aside">For all the miles<br />that make a life. <span>?</span></div></div><div className="wrap footer-bottom"><span>� 2026 Ruthikisha Travel</span><span>Made with care in Coimbatore.</span></div></footer> }

export default App


