import { useMemo, useState } from 'react'
import { Link, NavLink, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { formatINR } from './utils/formatINR'
import { useEffect } from 'react'
import { api } from './api'
import './Premium.css'
import './Future.css'
import './SeatMap.css'
import './CustomerBookings.css'
import AdminApp from './AdminApp'
import TicketQRCode from './TicketQRCode'

const sideCoach = '/images/WhatsApp%20Image%202026-09-29%20at%209.20.04%20AM.jpeg'
const frontCoach = '/images/WhatsApp%20Image%202026-09-29%20at%209.20.05%20AM.jpeg'

function Icon({ name, size = 18 }) {
  const paths = {
    arrow: <><path d="M4 12h15"/><path d="m13 6 6 6-6 6"/></>,
    pin: <><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,
    swap: <><path d="m16 3 4 4-4 4"/><path d="M20 7H4"/><path d="m8 21-4-4 4-4"/><path d="M4 17h16"/></>,
    calendar: <><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>,
    users: <><path d="M16 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="10" cy="7" r="4"/><path d="M20 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,
    star: <path d="m12 3 2.75 5.58 6.16.9-4.46 4.34 1.05 6.13L12 17.06l-5.5 2.89 1.05-6.13L3.1 9.48l6.16-.9L12 3Z"/>,
    clock: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
    bus: <><path d="M5 17V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v12"/><path d="M5 10h14M5 14h14M7 17v3m10-3v3"/><circle cx="8" cy="17" r="1"/><circle cx="16" cy="17" r="1"/></>,
    shield: <><path d="M12 22s8-4 8-11V5l-8-3-8 3v6c0 7 8 11 8 11Z"/><path d="m9 12 2 2 4-4"/></>,
    seat: <><path d="M7 18v-8a3 3 0 0 1 6 0v4h3a3 3 0 0 1 3 3v1H7Z"/><path d="M5 18v3m14-3v3"/></>,
    check: <path d="m5 12 4 4L19 6"/>,
    mail: <><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></>,
    phone: <path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1A19.4 19.4 0 0 1 5 12.6a19.8 19.8 0 0 1-3.1-8.7A2 2 0 0 1 3.9 1.7h3a2 2 0 0 1 2 1.7l.5 2.8a2 2 0 0 1-.6 1.7L7.5 9.2a16 16 0 0 0 7.3 7.3l1.3-1.3a2 2 0 0 1 1.7-.6l2.8.5a2 2 0 0 1 1.4 1.8Z"/>,
    map: <><path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Z"/><path d="M9 3v15m6-12v15"/></>,
    sparkle: <><path d="m12 3 1.6 5.4L19 10l-5.4 1.6L12 17l-1.6-5.4L5 10l5.4-1.6L12 3Z"/><path d="m19 16 .8 2.2L22 19l-2.2.8L19 22l-.8-2.2L16 19l2.2-.8L19 16Z"/></>,
  }
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{paths[name] || paths.sparkle}</svg>
}

function App() {
  const navigate = useNavigate()
  const [booking, setBooking] = useState(null)
  const [cities, setCities] = useState([])
  const [trip, setTrip] = useState({ from: 'Coimbatore', to: 'Chennai', date: new Date().toISOString().slice(0, 10), returnDate: '', passengers: 1 })
  useEffect(() => { api('/meta').then(data => setCities(data.cities)).catch(() => setCities([])) }, [])
  const updateBooking = (next) => setBooking(next)
  const search = () => navigate(`/search?from=${encodeURIComponent(trip.from)}&to=${encodeURIComponent(trip.to)}&date=${trip.date}`)
  const chooseBus = (bus) => { updateBooking({ ...booking, bus, trip }); navigate(`/bus/${bus.id}`) }
  const beginSeats = (bus) => { updateBooking({ ...booking, bus, trip }); navigate(`/bus/${bus.id}/seats`) }
  const selectSeats = (seats) => { updateBooking({ ...booking, seats }); navigate('/booking') }
  const finishPassengers = async (passenger) => { try { const people=passenger.passengers?.length?passenger.passengers:booking.seats.map(()=>({fullName:passenger.name,email:passenger.email,phone:passenger.phone}));const result=await api('/bookings',{method:'POST',body:JSON.stringify({scheduleId:booking.bus.scheduleId||booking.bus.id,travelDate:booking.trip.date,customer:{fullName:passenger.name,phone:passenger.phone,email:passenger.email},passengers:booking.seats.map((seatNumber,index)=>({...people[index],fullName:people[index].fullName||passenger.name,seatNumber:String(seatNumber),age:people[index].age?Number(people[index].age):undefined}))})});const next={...booking,passenger,id:result.booking.reference,bookingId:result.booking.id,bookingToken:result.booking.bookingToken,total:Number(result.booking.total),status:'Pending'};const saved=JSON.parse(sessionStorage.getItem('ruthikisha.booking-access')||'[]');sessionStorage.setItem('ruthikisha.booking-access',JSON.stringify([{id:result.booking.id,token:result.booking.bookingToken},...saved.filter(item=>item.id!==result.booking.id)]));updateBooking(next);navigate('/payment') } catch(error) { window.alert(error.message) } }
  const pay = async () => { try { const order=await api('/payments/order',{method:'POST',body:JSON.stringify({bookingId:booking.bookingId,bookingToken:booking.bookingToken})});if(!window.Razorpay) { await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.onload=resolve;script.onerror=reject;document.body.appendChild(script)}); } const checkout=new window.Razorpay({key:order.keyId,amount:order.amount,currency:order.currency,name:'Ruthikisha Travel',order_id:order.orderId,handler:async(response)=>{try{await api('/payments/verify',{method:'POST',headers:{Authorization:`Bearer ${booking.bookingToken}`},body:JSON.stringify({...response,bookingId:booking.bookingId,bookingToken:booking.bookingToken})});const next={...booking,status:'Confirmed'};updateBooking(next);navigate('/booking-confirmation')}catch(error){window.alert(error.message)}},modal:{ondismiss:()=>{}}});checkout.open()}catch(error){window.alert(error.message)} }
  return <Routes><Route path="/admin/*" element={<AdminApp/>}/><Route path="*" element={<><Header /><Routes>
    <Route path="/" element={<FutureHome trip={trip} setTrip={setTrip} search={search} cities={cities} />} />
    <Route path="/search" element={<SearchResults trip={trip} chooseBus={chooseBus} />} />
    <Route path="/bus/:id" element={<ScheduleDetailsPage beginSeats={beginSeats} booking={booking} />} />
    <Route path="/bus/:id/seats" element={<RealSeatSelection booking={booking} selectSeats={selectSeats} />} />
    <Route path="/seats/:id" element={<RealSeatSelection booking={booking} selectSeats={selectSeats} />} />
    <Route path="/booking" element={<PassengerBookingForm booking={booking} submit={finishPassengers} />} />
    <Route path="/payment" element={<RealPayment booking={booking} pay={pay} />} />
    <Route path="/booking-confirmation" element={<Confirmation booking={booking} />} />
    <Route path="/confirmation" element={<Confirmation booking={booking} />} />
    <Route path="/my-bookings" element={<MyBookings />} />
    <Route path="/about" element={<About />} />
    <Route path="/contact" element={<Contact />} />
    <Route path="*" element={<NotFound />} />
  </Routes><Footer /></>}/></Routes>
}

function Header() {
  const [open, setOpen] = useState(false)
  return <header className="topbar"><div className="topbar-inner wrap"><Link className="brand" to="/" aria-label="Ruthikisha Travel home"><span className="brand-mark"><Icon name="sparkle" size={20}/></span><span>ruthikisha<small>TRAVEL, THOUGHTFULLY</small></span></Link><button className="menu-toggle" aria-label={open ? 'Close navigation' : 'Open navigation'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? '×' : <span className="hamburger"><i/><i/></span>}</button><nav className={open ? 'nav-links open' : 'nav-links'}><NavLink end to="/" onClick={() => setOpen(false)}>Home</NavLink><a href="/#journeys" onClick={() => setOpen(false)}>Destinations</a><NavLink to="/about" onClick={() => setOpen(false)}>Our story</NavLink><NavLink to="/contact" onClick={() => setOpen(false)}>Contact</NavLink><NavLink to="/my-bookings" onClick={() => setOpen(false)}>My bookings</NavLink><Link className="button nav-cta" to="/#search" onClick={() => setOpen(false)}>Book a journey <Icon name="arrow" size={16}/></Link></nav></div></header>
}

function SearchForm({ trip, setTrip, search, cities }) {
  const set = (key, value) => setTrip({ ...trip, [key]: value })
  return <form className="search-form" onSubmit={(event) => { event.preventDefault(); search() }}>
    <label><span><Icon name="pin"/> FROM</span><select required value={trip.from} onChange={(event) => set('from', event.target.value)}>{cities.map((city) => <option key={city}>{city}</option>)}</select></label>
    <button className="swap-button" type="button" aria-label="Swap origin and destination" onClick={() => setTrip({ ...trip, from: trip.to, to: trip.from })}><Icon name="swap"/></button>
    <label><span><Icon name="pin"/> TO</span><select required value={trip.to} onChange={(event) => set('to', event.target.value)}>{cities.map((city) => <option key={city}>{city}</option>)}</select></label>
    <label><span><Icon name="calendar"/> DEPARTURE</span><input required type="date" value={trip.date} onChange={(event) => set('date', event.target.value)}/></label>
    <label><span><Icon name="calendar"/> RETURN <small>OPTIONAL</small></span><input type="date" min={trip.date} value={trip.returnDate} onChange={(event) => set('returnDate', event.target.value)}/></label>
    <label><span><Icon name="users"/> TRAVELLERS</span><select value={trip.passengers} onChange={(event) => set('passengers', Number(event.target.value))}>{[1,2,3,4,5,6].map((n) => <option key={n} value={n}>{n} {n === 1 ? 'passenger' : 'passengers'}</option>)}</select></label>
    <button className="button search-button">Find buses <Icon name="arrow" size={17}/></button>
  </form>
}

function usePublicContent(){const [content,setContent]=useState({});useEffect(()=>{api('/content').then(data=>setContent(data.content||{})).catch(()=>{})},[]);return content}

function FutureHome({ trip, setTrip, search, cities }) {
  const content=usePublicContent()
  const [journeys,setJourneys]=useState([]);useEffect(()=>{api('/routes').then(data=>setJourneys(data.routes.filter(route=>route.from==='Coimbatore').map(route=>({...route,duration:`${Math.floor(route.durationMinutes/60)}h ${String(route.durationMinutes%60).padStart(2,'0')}m`,time:route.distanceKm?`${route.distanceKm} km route`:'South India',fare:'see fares'})))).catch(()=>setJourneys([]))},[])
  const featuredRoutes=Array.isArray(content['home.featuredRoutes'])?content['home.featuredRoutes']:[]
  const visibleJourneys=featuredRoutes.length?journeys.filter(route=>featuredRoutes.includes(route.to)||featuredRoutes.includes(route.id)):journeys
  const heroWords=String(content['home.heroTitle']||'YOUR JOURNEY STARTS HERE').replace(/[.]\s*$/,'').split(/\s+/)
  const explore = (to) => { setTrip({ ...trip, from: 'Coimbatore', to }); document.querySelector('#search')?.scrollIntoView({ behavior: 'smooth', block: 'center' }) }
  return <main className="future-home">
    <section className="hero future-hero"><img className="hero-photo" src={content['home.heroImage']||frontCoach} alt="Passenger coach beside the green hills of South India" fetchPriority="high"/><div className="future-hero-shade"/><div className="hero-copy wrap future-hero-copy"><span className="eyebrow eyebrow-light"><Icon name="sparkle" size={14}/> THE FUTURE OF THE JOURNEY</span><h1>{heroWords.map((word,index)=><span key={`${index}-${word}`}>{word}{index===heroWords.length-1&&<span className="hero-period">.</span>}</span>)}</h1><p>{content['home.heroSubtitle']||<>Comfortable journeys.<br/>Thoughtfully designed.</>}</p><a href="#search" className="hero-link">Set your direction <Icon name="arrow"/></a></div><div className="hero-coordinate">11°00' N <i/> 76°57' E <small>COIMBATORE · 411 KM TO CHENNAI</small></div><a className="scroll-cue" href="#journeys"><span/> SCROLL TO EXPLORE</a>
      <div className="search-shell wrap" id="search"><div className="search-heading"><div><span className="eyebrow">YOUR NEXT DEPARTURE</span><h2>Set your direction.</h2></div><div className="search-badge"><Icon name="shield" size={15}/> Secure booking</div></div><SearchForm trip={trip} setTrip={setTrip} search={search} cities={cities}/></div>
    </section>
    <section className="journey-explorer" id="journeys"><div className="wrap journey-heading"><div><span className="eyebrow">01 / JOURNEY EXPLORER</span><h2>From here,<br/><em>the map opens.</em></h2></div><p>One considered departure.<br/>A dozen ways to feel somewhere new.</p></div><div className="wrap journey-map"><div className="map-origin"><span className="origin-pulse"/><small>YOU ARE HERE</small><strong>Coimbatore</strong><span className="coordinates">11°00' N · 76°57' E</span></div><svg className="journey-svg" viewBox="0 0 1000 180" preserveAspectRatio="none" aria-hidden="true"><path className="journey-path" d="M0 94 C145 94 126 34 276 34 S405 141 535 141 707 57 790 57 893 119 1000 119"/><path className="journey-path journey-path-glow" d="M0 94 C145 94 126 34 276 34 S405 141 535 141 707 57 790 57 893 119 1000 119"/></svg><div className="journey-stations">{visibleJourneys.map((journey,index)=><button className={`journey-station station-${index+1}`} key={journey.to} onClick={()=>explore(journey.to)}><span className="station-node"/><small>0{index+1} / DESTINATION</small><strong>{journey.to}</strong><span className="station-info"><span><Icon name="clock" size={13}/>{journey.duration}</span><span>{journey.time}</span><b>From {journey.fare}</b></span><span className="station-availability">View journey <Icon name="arrow" size={14}/></span></button>)}</div></div></section>
    <BusShowcase/>
    <section className="destination-experience"><img src={sideCoach} alt="Passenger coach ready for the road across South India" loading="lazy"/><div className="destination-wash"/><div className="destination-frame wrap"><span className="eyebrow eyebrow-light">02 / THE ROAD BETWEEN</span><h2>GO<br/><em>BEYOND.</em></h2><div className="destination-caption"><span>THE JOURNEY IS PART OF THE ARRIVAL</span><Link to="/about">Why we travel <Icon name="arrow"/></Link></div></div><span className="destination-coordinate">ON THE ROAD · SOUTH INDIA</span></section>
    <section className="future-manifesto wrap"><span className="eyebrow">TRAVEL, THOUGHTFULLY</span><p>Good journeys are made of the <em>moments between.</em></p><div className="manifesto-bottom"><span>SPACE TO SETTLE IN</span><i/><span>PEOPLE WHO CARE</span><i/><span>CLEAR FROM THE START</span></div></section>
    <section className="future-cta"><div className="wrap future-cta-inner"><span className="eyebrow eyebrow-light">YOUR NEXT CHAPTER IS OUT THERE</span><h2>WHERE WILL<br/><em>YOU GO NEXT?</em></h2><Link className="button button-cream" to="#search">Book your journey <Icon name="arrow"/></Link><span className="cta-coordinate">11°00' N&nbsp; / &nbsp;76°57' E</span></div></section>
  </main>
}

function BusShowcase() {
  const [tilt, setTilt] = useState({ x: 0, y: 0 })
  const move = (event) => { if (window.matchMedia('(max-width: 760px)').matches) return; const box = event.currentTarget.getBoundingClientRect(); setTilt({ x: ((event.clientY-box.top)/box.height-.5)*-5, y: ((event.clientX-box.left)/box.width-.5)*7 }) }
  return <section className="showcase-section"><div className="showcase-wrap wrap"><div className="showcase-copy"><span className="eyebrow eyebrow-light">THE RUTHIKISHA RIDE</span><h2>Made for a softer<br/><em>kind of distance.</em></h2><p>Settle into a good seat. We’ll take care of the miles between here and there.</p><div className="showcase-points"><span><Icon name="seat"/> Comfort, considered</span><span><Icon name="shield"/> Safe, trusted journeys</span><span><Icon name="map"/> Routes close to home</span></div></div><div className="showcase-stage" onPointerMove={move} onPointerLeave={()=>setTilt({x:0,y:0})}><div className="showcase-orbit orbit-one"/><div className="showcase-orbit orbit-two"/><div className="showcase-glow"/><div className="showcase-road"><i/><i/><i/></div><div className="floating-note note-comfort"><Icon name="seat"/><span>Comfortable journey<small>Room to settle in</small></span></div><div className="floating-note note-safety"><Icon name="shield"/><span>Travel with care<small>Trusted operators</small></span></div><img className="showcase-bus" src={sideCoach} alt="Passenger bus shown in a subtle floating showcase" loading="lazy" style={{'--tilt-x':`${tilt.x}deg`,'--tilt-y':`${tilt.y}deg`}}/><div className="showcase-reflection"/></div></div></section>
}

function SearchResults({ trip, chooseBus }) {
  const [params] = useSearchParams(); const from = params.get('from') || trip.from; const to = params.get('to') || trip.to
  const date=params.get('date')||trip.date; const [sort,setSort]=useState('Recommended'); const [acOnly,setAcOnly]=useState(false); const [maxPrice,setMaxPrice]=useState(2000); const [results,setResults]=useState([]); const [error,setError]=useState('')
  useEffect(()=>{api(`/search?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}&date=${date}`).then(d=>setResults(d.schedules.map(s=>({...s,scheduleId:s.id,amenities:Array.isArray(s.amenities)?s.amenities:[],seats:s.seats,image:s.image||frontCoach})))).catch(e=>{setResults([]);setError(e.message)})},[from,to,date])
  const filtered=useMemo(()=>{let list=results.filter(bus=>bus.price<=maxPrice);if(acOnly)list=list.filter(bus=>/AC|Volvo/i.test(bus.type));if(sort==='Lowest price')list.sort((a,b)=>a.price-b.price);return list},[results,acOnly,maxPrice,sort])
  return <main className="page wrap"><div className="page-kicker"><span className="eyebrow">A ROAD WELL CHOSEN</span><span>South India · Coach travel</span></div><h1 className="page-title">{from} <Icon name="arrow" size={27}/> {to}</h1><p className="page-subtitle">{filtered.length} buses for {date}. Pick the ride that feels right.</p>{error&&<p role="status">{error}</p>}<div className="results-layout"><aside className="filter-panel"><h3>Make it your kind of ride</h3><label className="check-label"><input type="checkbox" checked={acOnly} onChange={(event)=>setAcOnly(event.target.checked)}/>Air conditioned</label><label className="filter-caption" htmlFor="price">MAX FARE <b>{formatINR(maxPrice)}</b></label><input id="price" type="range" min="400" max="2000" step="100" value={maxPrice} onChange={(event)=>setMaxPrice(Number(event.target.value))}/><span className="filter-caption">AMENITIES</span><p><Icon name="seat" size={15}/> Charging available</p><p><Icon name="shield" size={15}/> Onboard support</p></aside><div className="bus-list"><div className="sort-bar"><span>{filtered.length} thoughtful {filtered.length===1?'option':'options'}</span><label>Sort by <select value={sort} onChange={(event)=>setSort(event.target.value)}><option>Recommended</option><option>Lowest price</option></select></label></div>{filtered.length?filtered.map((bus,index)=><BusCard key={bus.id} bus={bus} chooseBus={chooseBus} image={index%2===0?(bus.image||frontCoach):(bus.image||sideCoach)}/>):<div className="empty-state panel"><h2>{error?'Journey search is unavailable.':'No buses on this route just yet.'}</h2><p>{error||'Try another route or date.'}</p><Link className="button" to="/">Change your search <Icon name="arrow"/></Link></div>}</div></div></main>
}

function BusCard({bus,chooseBus,image}) { return <article className="bus-card"><img className="bus-card-image" src={image} alt={`${bus.operator} passenger coach`} loading="lazy"/><div className="bus-card-content"><div className="bus-card-main"><div className="operator"><span className="operator-mark"><Icon name="bus"/></span><span><b>{bus.operator}</b><small>{bus.type}</small></span></div><div className="bus-times"><div><b>{bus.depart}</b><small>{bus.from}</small></div><span className="duration">{bus.duration}<i/></span><div><b>{bus.arrive}</b><small>{bus.to}</small></div></div><div className="bus-price"><span>From</span><b>{formatINR(bus.price)}</b><small>{bus.seats} seats left</small></div></div><div className="bus-card-bottom"><span>{bus.amenities.join(' · ')}</span><button className="button button-small" onClick={()=>chooseBus(bus)}>View journey <Icon name="arrow" size={15}/></button></div></div></article> }

function ScheduleDetailsPage({beginSeats,booking}){const {id}=useParams();const date=booking?.trip?.date||new Date().toISOString().slice(0,10);const [bus,setBus]=useState(booking?.bus?.id===id?booking.bus:null);const [error,setError]=useState('');useEffect(()=>{if(booking?.bus?.id===id)return;api(`/schedules/${id}?date=${date}`).then(result=>setBus({...result.schedule,scheduleId:result.schedule.id,amenities:Array.isArray(result.schedule.amenities)?result.schedule.amenities:[],image:result.schedule.image||frontCoach})).catch(e=>setError(e.message))},[id,date,booking?.bus?.id]);if(error)return <main className="page wrap"><h1 className="page-title">Journey details are unavailable.</h1><p className="page-subtitle">{error}</p><Link className="button" to="/search">Search journeys</Link></main>;if(!bus)return <main className="page wrap"><p>Loading journey details…</p></main>;return <main className="page wrap"><span className="eyebrow">A CLOSER LOOK</span><h1 className="page-title">The {bus.operator}<br/><em>experience.</em></h1><p className="page-subtitle">{bus.type} · {bus.seats} seats available · {date}</p><figure className="bus-detail-photo"><img src={bus.image||frontCoach} alt={`${bus.operator} coach for the ${bus.from} to ${bus.to} journey`} fetchPriority="high"/><figcaption>Ready for the road · Ruthikisha Travel</figcaption></figure><div className="detail-columns"><section className="panel detail-panel"><h2>{bus.from} <Icon name="arrow"/> {bus.to}</h2><div className="timeline"><div><b>{bus.depart}</b><span><strong>{bus.from}</strong></span></div><div><b>{bus.arrive}</b><span><strong>{bus.to}</strong></span></div></div><h3>Comforts on board</h3><div className="amenity-list">{bus.amenities.map(item=><span key={item}><Icon name="check" size={15}/>{item}</span>)}</div></section><aside className="panel ride-summary"><span className="eyebrow">YOUR RIDE</span><h2>{bus.operator}</h2><p>{bus.from} to {bus.to}</p><p>{bus.depart} · {bus.duration} · {bus.arrive}</p><p>{bus.seats} seats available</p><hr/><h3>{formatINR(bus.price)} <small>/ seat</small></h3><button className="button full-button" onClick={()=>beginSeats(bus)}>Choose your seat <Icon name="arrow"/></button></aside></div></main>}

function RealSeatSelection({booking,selectSeats}){const bus=booking?.bus;const [seats,setSeats]=useState([]);const [selected,setSelected]=useState([]);const [error,setError]=useState('');const count=booking?.trip?.passengers||1;useEffect(()=>{if(!bus?.scheduleId)return;api(`/schedules/${bus.scheduleId}/seats?date=${booking.trip.date}`).then(data=>setSeats(data.seats)).catch(err=>setError(err.message))},[bus?.scheduleId,booking?.trip?.date]);if(!bus)return <NavigateHome/>;const unavailable=new Set(seats.filter(seat=>seat.unavailable||!seat.active).map(seat=>seat.seat_number));const seatCount=seats.length;const seatColumns=Number(bus.seatLayout?.columns)||4;const aisleAfter=Number(bus.seatLayout?.aisleAfter)||0;const gridStyle={gridTemplateColumns:`repeat(${seatColumns+(aisleAfter?1:0)},minmax(0,1fr))`};if(error)return <main className="page wrap"><h1 className="page-title">Live seats are unavailable.</h1><p className="page-subtitle">{error}</p><Link className="button" to="/search">Return to search</Link></main>;return <main className="page wrap"><span className="eyebrow">MAKE IT YOURS</span><h1 className="page-title">Pick your <em>place.</em></h1><p className="page-subtitle">{bus.from} to {bus.to} · {bus.operator} · Choose up to {count} seats</p><div className="seat-layout"><section className="panel seat-panel"><div className="driver"><span>FRONT OF BUS</span><Icon name="bus"/></div><div className="seat-grid" style={gridStyle}>{seats.map(seat=>{const number=seat.seat_number;return <button key={seat.seat_number} style={{gridRow:seat.row_number,gridColumn:Number(seat.column_number)+(aisleAfter&&Number(seat.column_number)>aisleAfter?1:0)}} type="button" aria-label={`Seat ${seat.seat_number}${unavailable.has(number)?', unavailable':selected.includes(number)?', selected':', available'}`} aria-pressed={selected.includes(number)} disabled={unavailable.has(number)} className={`seat ${unavailable.has(number)?'occupied':''} ${selected.includes(number)?'selected':''}`} onClick={()=>setSelected(current=>current.includes(number)?current.filter(value=>value!==number):current.length<count?[...current,number]:current)}>{seat.seat_number}</button>})}</div><div className="seat-legend"><span><i/>Available</span><span><i className="selected-key"/>Selected</span><span><i className="occupied-key"/>Booked or held</span></div></section><aside className="panel seat-summary"><span className="eyebrow">BOOKING SUMMARY</span><h2>{selected.length?`${selected.length} selected`:'Choose a seat'}</h2>{selected.map(number=><p key={number}>Seat {number}<b>{formatINR(bus.price)}</b></p>)}<hr/><p>Passenger limit <b>{count}</b></p><p>Available seats <b>{seatCount-unavailable.size}</b></p><p>Seat fare <b>{formatINR(bus.price*selected.length)}</b></p><button className="button full-button" disabled={!selected.length} onClick={()=>selectSeats(selected)}>Continue <Icon name="arrow"/></button></aside></div></main>}
function NavigateHome(){return <main className="page wrap"><h1 className="page-title">Choose your ride first.</h1><Link className="button" to="/search">Find a bus <Icon name="arrow"/></Link></main>}
function PassengerBookingForm({booking,submit}){const bus=booking?.bus;const [contact,setContact]=useState({email:'',phone:''}),[people,setPeople]=useState(()=>booking?.seats?.map(()=>({fullName:'',age:'',gender:'PREFER_NOT_TO_SAY'}))||[]),[working,setWorking]=useState(false);if(!bus||!booking?.seats?.length)return <NavigateHome/>;const fare=bus.price*booking.seats.length;const update=(index,key,value)=>setPeople(current=>current.map((person,i)=>i===index?{...person,[key]:value}:person));return <main className="page wrap"><span className="eyebrow">ALMOST THERE</span><h1 className="page-title">The details, then <em>off you go.</em></h1><div className="detail-columns"><form className="panel form-panel" onSubmit={async event=>{event.preventDefault();setWorking(true);try{await submit({name:people[0]?.fullName,email:contact.email,phone:contact.phone,passengers:people})}finally{setWorking(false)}}}><h2>Passenger and contact details</h2><p className="muted">Enter each traveller as it appears on their travel ID.</p>{people.map((person,index)=><fieldset className="passenger-fields" key={booking.seats[index]}><legend>Passenger {index+1} · Seat {booking.seats[index]}</legend><label>FULL NAME<input required autoComplete={index===0?'name':'off'} value={person.fullName} onChange={event=>update(index,'fullName',event.target.value)}/></label><div className="passenger-row"><label>AGE<input type="number" min="1" max="120" value={person.age} onChange={event=>update(index,'age',event.target.value)}/></label><label>GENDER<select value={person.gender} onChange={event=>update(index,'gender',event.target.value)}><option value="PREFER_NOT_TO_SAY">Prefer not to say</option><option value="FEMALE">Female</option><option value="MALE">Male</option><option value="OTHER">Other</option></select></label></div></fieldset>)}<label>EMAIL ADDRESS<input required type="email" autoComplete="email" value={contact.email} onChange={event=>setContact({...contact,email:event.target.value})}/></label><label>PHONE NUMBER<input required type="tel" autoComplete="tel" minLength="10" value={contact.phone} onChange={event=>setContact({...contact,phone:event.target.value})}/></label><button className="button" disabled={working}>{working?'Securing your seats…':'Continue to payment'} <Icon name="arrow"/></button></form><aside className="panel ride-summary"><span className="eyebrow">JOURNEY SUMMARY</span><h2>{bus.from} <Icon name="arrow"/> {bus.to}</h2><p>{bus.operator} · {bus.type}</p><p>{booking.trip?.date} · {bus.depart} – {bus.arrive}</p><p>Seats {booking.seats.map(n=>String(n)).join(', ')}</p><hr/><p>Seat fare <b>{formatINR(fare)}</b></p><p>Convenience fee <b>{formatINR(bus.convenienceFee||25)}</b></p><p>Tax <b>{formatINR(Math.round(fare*Number(bus.taxPercent||0))/100)}</b></p><h3>Total <b>{formatINR(fare+(bus.convenienceFee||25)+Math.round(fare*Number(bus.taxPercent||0))/100)}</b></h3></aside></div></main>}
function RealPayment({booking,pay}) { const [working,setWorking]=useState(false);if(!booking?.bus)return <NavigateHome/>;return <main className="page wrap payment-page"><span className="eyebrow">SECURE CHECKOUT</span><h1 className="page-title">Make it <em>official.</em></h1><section className="panel form-panel"><h2>Continue with Razorpay</h2><p>Pay securely through Razorpay. The ticket is confirmed only after the server verifies your captured payment.</p><p><b>{booking.bus.from} to {booking.bus.to}</b></p><p>{booking.trip?.date} · {booking.bus.operator} · Seats {booking.seats.map(seat=>String(seat)).join(', ')}</p><h3>Total <b>{formatINR(booking.total)}</b></h3><button className="button" disabled={working||!booking.bookingId||!booking.bookingToken} onClick={async()=>{setWorking(true);try{await pay()}finally{setWorking(false)}}}>{working?'Opening secure checkout…':`Pay ${formatINR(booking.total)}`} <Icon name="arrow"/></button><small className="payment-note">Checkout requires Razorpay credentials to be configured on the server.</small></section></main> }
function Confirmation({booking}) { if(!booking?.bus)return <NavigateHome/>; return <main className="page wrap confirmation"><div className="success-mark"><Icon name="check" size={25}/></div><span className="eyebrow">YOU’RE ALL SET</span><h1 className="page-title">Your journey is <em>booked.</em></h1><p className="page-subtitle">A lovely trip is just around the corner.</p><section className="panel ticket"><div className="ticket-top"><span>BOOKING REFERENCE</span><b>{booking.id}</b></div><h2>{booking.bus.from} <Icon name="arrow"/> {booking.bus.to}</h2><p>{booking.bus.operator} · {booking.trip?.date} · Departure {booking.bus.depart} · Arrival {booking.bus.arrive}</p><hr/><div className="ticket-details"><span>Passenger<b>{booking.passenger?.name}</b></span><span>Bus<b>{booking.bus.operator}</b></span><span>Seats<b>{booking.seats.map((n)=>String(n)).join(', ')}</b></span><span>Amount paid<b>{formatINR(booking.total)}</b></span><span>Payment status<b>PAID</b></span></div><div className="ticket-qr-wrap"><TicketQRCode reference={booking.id}/><small>Scan to identify this ticket</small></div></section><div className="confirmation-actions"><button className="button" onClick={()=>window.print()}>Download / print ticket <Icon name="arrow"/></button><Link className="button button-outline" to="/my-bookings">View my bookings</Link><Link className="text-link" to="/">Go home</Link></div></main> }
function LegacyMyBookings() { return null }
void LegacyMyBookings
function MyBookings() {
  const [history,setHistory]=useState([])
  const [message,setMessage]=useState('')
  useEffect(()=>{const saved=JSON.parse(sessionStorage.getItem('ruthikisha.booking-access')||'[]');Promise.all(saved.map(async item=>{try{const data=await api(`/bookings/${item.id}`,{headers:{Authorization:`Bearer ${item.token}`}});return {...data.booking,accessToken:item.token}}catch{return null}})).then(items=>setHistory(items.filter(Boolean)))},[])
  const cancel=async item=>{const paid=item.payment_status==='PAID';const action=paid?'request cancellation for':'cancel';if(!window.confirm(`Would you like to ${action} ${item.reference}?${paid?' The support team will review your refund request.':' This releases your seats.'}`))return;try{const result=await api(`/bookings/${item.id}/cancel`,{method:'POST',headers:{Authorization:`Bearer ${item.accessToken}`},body:JSON.stringify({reason:'Requested by customer from My Bookings'})});setHistory(current=>current.map(booking=>booking.id===item.id?{...booking,status:result.status||booking.status,cancellation_request_status:result.cancellationRequestStatus||booking.cancellation_request_status}:booking));setMessage(result.status==='CANCELLED'?`${item.reference} has been cancelled and its seats released.`:`Cancellation request for ${item.reference} has been sent to support.`)}catch(error){setMessage(error.message)}}
  return <main className="page wrap"><span className="eyebrow">YOUR TRIPS</span><h1 className="page-title">A little road <em>time.</em></h1><p className="page-subtitle">Your Ruthikisha journeys, all in one place.</p>{message&&<p role="status" className="booking-message">{message}</p>}{history.length?<div className="history-list">{history.map(item=><article className="panel history-card" key={item.id}><img className="history-thumb" src={frontCoach} alt="Passenger coach" loading="lazy"/><div className="history-copy"><span className="eyebrow">{item.reference} · {item.travel_date}</span><h2>{item.from_city} <Icon name="arrow"/> {item.to_city}</h2><p>{item.bus_name} · Seats {item.passengers.map(p=>p.seat).join(', ')}</p>{item.cancellation_request_status==='REQUESTED'&&<small className="cancellation-pending">Cancellation request under review</small>}</div><div className="history-end"><b>{formatINR(item.total)}</b><span className="status">{item.status}</span>{['PENDING','CONFIRMED'].includes(item.status)&&item.cancellation_request_status!=='REQUESTED'&&<button type="button" className="cancel-booking" onClick={()=>cancel(item)}>{item.payment_status==='PAID'?'Request cancellation':'Cancel booking'}</button>}</div></article>)}</div>:<section className="panel empty-state"><h2>Your next journey is waiting.</h2><p>Bookings made in this browser will appear after checkout.</p><Link className="button" to="/">Find your journey <Icon name="arrow"/></Link></section>}</main>
}function About() { const content=usePublicContent(); return <main className="page wrap"><span className="eyebrow">ROOTED IN COIMBATORE</span><h1 className="page-title">A more human way<br/>to <em>move through South India.</em></h1><div className="about-layout"><section className="about-story"><p className="lead">Ruthikisha Travel began with a simple thought: getting there could feel a little more human.</p><p>{content['about.story']||'We’re a Coimbatore-based travel team building a better way to explore South India. We bring trusted bus operators, comfortable journeys and thoughtful service together, so you can spend less time figuring it out and more time looking forward.'}</p><p>Whether it’s a weekend visit, a long-awaited reunion or a new city on your map, we’re happy to be part of the way.</p><Link className="button" to="/search">Find your next journey <Icon name="arrow"/></Link><div className="about-stats"><span><b>5</b><small>cities connected</small></span><span><b>4.8</b><small>traveller rating</small></span><span><b>24/7</b><small>journey access</small></span></div></section><figure className="about-photo"><img src={sideCoach} alt="Passenger coach on a road surrounded by green hills" loading="lazy"/><figcaption>Made with care in Coimbatore.</figcaption></figure></div></main> }
function Contact() {
  const content=usePublicContent()
  const [form,setForm]=useState({name:'',email:'',message:''})
  const [working,setWorking]=useState(false)
  const [error,setError]=useState('')
  const [sent,setSent]=useState(false)
  const submit=async event=>{event.preventDefault();setWorking(true);setError('');try{await api('/contact',{method:'POST',body:JSON.stringify(form)});setSent(true)}catch(err){setError(err.message)}finally{setWorking(false)}}
  return <main className="page wrap"><span className="eyebrow">A REAL PERSON IS RIGHT HERE</span><h1 className="page-title">Let’s have a <em>conversation.</em></h1><p className="page-subtitle">Questions, ideas, or just want to say hello? We’d love to hear from you.</p><div className="contact-banner"><img src={frontCoach} alt="A Ruthikisha coach ready to welcome travellers" loading="lazy"/></div><div className="detail-columns contact-layout"><section className="panel contact-info"><h2>Come say hello.</h2><p><Icon name="pin"/> {content['contact.address']||'Coimbatore, Tamil Nadu, India'}</p><p><Icon name="phone"/> {content['contact.phone']||'+91 422 456 7890'}</p><p><Icon name="mail"/> {content['contact.email']||'hello@ruthikishatravel.in'}</p><h3>Here when you need us</h3><p>{content['contact.supportHours']||'Our local support team is available every day, 8am–8pm.'}</p><div className="eyebrow">QUICK QUESTIONS</div>{[['When will my ticket arrive?','Your confirmation is ready right after checkout.'],['Can I change my trip?','Contact our team and we’ll guide you through your operator’s options.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section><form className="panel form-panel" onSubmit={submit}><h2>Send us a note</h2>{sent?<p className="success-message" role="status">Thanks for reaching out. Your message is saved for our team.</p>:<><label>YOUR NAME<input required minLength="2" maxLength="120" value={form.name} onChange={event=>setForm({...form,name:event.target.value})} placeholder="Your name"/></label><label>EMAIL ADDRESS<input required type="email" maxLength="254" value={form.email} onChange={event=>setForm({...form,email:event.target.value})} placeholder="you@example.com"/></label><label>WHAT’S ON YOUR MIND?<textarea required minLength="10" maxLength="5000" rows="5" value={form.message} onChange={event=>setForm({...form,message:event.target.value})} placeholder="Write us a note"/></label>{error&&<p className="contact-error" role="alert">{error}</p>}<button className="button" disabled={working}>{working?'Sending…':'Send your note'} <Icon name="arrow"/></button></>}</form></div></main>
}function NotFound() { return <main className="page wrap not-found"><span className="eyebrow">WE TOOK A WRONG TURN</span><h1 className="page-title">This road ends <em>here.</em></h1><p className="page-subtitle">Let’s get you back to somewhere lovely.</p><Link className="button" to="/">Back to home <Icon name="arrow"/></Link></main> }
function Footer() { return <footer className="site-footer"><div className="wrap footer-main"><div className="footer-brand"><Link className="brand brand-light" to="/"><span className="brand-mark"><Icon name="sparkle" size={18}/></span><span>ruthikisha<small>TRAVEL, THOUGHTFULLY</small></span></Link><p>Good journeys begin here.<br/>Coimbatore, Tamil Nadu, India.</p></div><div><span className="footer-label">EXPLORE</span><Link to="/search">Find a bus</Link><Link to="/about">Our story</Link><Link to="/contact">Get in touch</Link></div><div><span className="footer-label">YOUR TRAVEL</span><Link to="/my-bookings">My bookings</Link><Link to="/contact">Help and support</Link><a href="/#journeys">Popular routes</a></div><div className="footer-aside">For all the miles<br/>that make a life. <Icon name="sparkle" size={18}/></div></div><div className="wrap footer-bottom"><span>© 2026 Ruthikisha Travel</span><span>Made with care in Coimbatore.</span></div></footer> }

export default App

















